### PR TITLE
Osmocom updates for v3.3 production run

### PR DESCRIPTION
**Pull request by cibomahto**
This is a blanket pull request for the board changes requested in the Osmocom issue tracker:
https://osmocom.org/projects/openvizsla/issues

As discussed in https://github.com/openvizsla/ov_ftdi/pull/43#issuecomment-797761605 ,  we will collect all of these changes before requesting a merge.

### CODE REVIEW

**Comment by cibomahto** [comment]
For 'Move VBUS away from ground pad':
VBUS too close to GND

**Comment by msweef** [comment]
regarding 8f46340: see my update on https://osmocom.org/issues/5074#note-4, this introduced a possible clearance issue on a power wire on bottom side of P4.

**Comment by cibomahto** [comment]
Note: I force-pushed a commit by mistake, then reverted it with a separate force-push.

**Comment by laf0rge** [comment]
I think we're done now with all v3.3 changes now, as far as I know.  MAybe it's time to un-WIP the pull request and get it merged?

**Comment by laf0rge** [comment]
@tmbinc I'm not familiar with how WIP PR work in github,, but it seems like you should be able to un-WIP it and then look at merging it.  This latest state of v3.3 is what sysmocom is putting in production right now.  All changes are cosmetic and/or manufacturability related, no logical changes and hence obviously no gateware/software changes are required.

**Comment by tmbinc** [comment]
Thank you for the changes!

**Pull request merged**
