### PR TITLE
Osmocom requested changes, second batch

### PR DESCRIPTION
**Pull request by cibomahto**
Some schematic properties were rotated, making it difficult to read them
in the PDF.

* Search for all rotated text using the query:
((ObjectKind = 'Parameter') or (ObjectKind = 'Comment')
or (ObjectKind = 'Designator') or (ObjectKind = 'Net Label'))
And (Orientation <> '0 Degrees')
* Manually rotate and re-position.

### CODE REVIEW

**Comment by laf0rge** [comment]
Thanks.  However, I'm not seeing an updated PDF rendering and/or file rename of hardware/ov_3.2_design.pdf yet.

**Comment by cibomahto** [comment]
> Thanks. However, I'm not seeing an updated PDF rendering and/or file rename of hardware/ov_3.2_design.pdf yet.

Understood. I had an implementation question here: https://osmocom.org/issues/5159

**Comment by msweef** [comment]
> I had an implementation question here: https://osmocom.org/issues/5159

Ah, ok - i didn't see this either, as you forgot to add me as watcher! :p

**Comment by laf0rge** [comment]
@tmbinc please consider merging this PR now, @msweef and I have already put the first batch of v3.4 into production now.

It would also be great if you could push tags
* hardware_v3.3 for d6f3ff5502b4743e2228c15f93ad8d028ab9a635
* hardware_v3.4 for the new master after merging this PR
* hardware_v3.2 for 36753a4d1943270afb4089d75cc24a975e0c581e

Thanks!

**Pull request merged**
