### PR TITLE
Remove sponsor logos from PCB

### PR DESCRIPTION
**Pull request by cibomahto**
Fix for issue: https://osmocom.org/issues/5062

Was:
before

Now:
after

### CODE REVIEW

**Comment by laf0rge** [comment]
Thanks. I'm not sure how much effort it is, but if it's just one or two clicks, then it might make sense to also update the output files (gerber, ...) in every commit to make sure it's in sync with the Altium design files.

@tmbinc for your information: sysmocom is planning a new production batch and there are a number of change requests that we have collected at https://osmocom.org/projects/openvizsla/issues

@cibomahto is going to implement those as  we don't have Altium at sysmocom. 

The rationale for this specific change is that those sponsors may very well have been contrbuting by discounts or free parts some 6+ years ago, but they should not get free advertisement for any manufacturing runs today, where they have no involvement and no contribution.

**Comment by cibomahto** [comment]
@laf0rge I'll update the gerbers on all following ones. By mistake I made these changes before updating the gerber output settings

**Comment by laf0rge** [comment]
ok, LGTM.  I should be getting pormissions to merge the PR shortly, thanks to @tmbinc

**Comment by tmbinc** [comment]
Can you please re-base this commit? Thanks!

**Comment by cibomahto** [comment]
Hi @tmbinc , the change from this pull request were already accepted as part of #44 :
https://github.com/openvizsla/ov_ftdi/pull/44/commits/b83d274f97a02192d8c2bfb77aa3c2c7f0d91efc

Re-basing is unfortunately somewhat problematic with Altium files, since they are in a binary format, and the changes are cumulative. To work around this I'll now release each change separately, and wait for it to be merged before sending the next pull request.

**Comment by laf0rge** [comment]
On Fri, Mar 12, 2021 at 12:21:07PM -0800, Matthew Mets wrote:
> Re-basing is unfortunately somewhat problematic with Altium files, since they are in a binary format, and the changes are cumulative. To work around this I'll now release each change separately, and wait for it to be merged before sending the next pull request.

In order to minimize the work for @tmbinc and to enable you to continue working
efficiently, I'd say it's probably ok to just collect
all of the pending hardware design file changes in one PR (with a growing list of commits
that is updated again and again) until we (Martin + myself from sysmocom) agree
it looks like what we wanted and then @tmbinc merges that PR once we are done with
all of them.

-- 
- Harald Welte ***@***.***>           http://laforge.gnumonks.org/
============================================================================
"Privacy in residential applications is a desirable marketing option."
                                                  (ETSI EN 300 175-7 Ch. A6)

**Comment by cibomahto** [comment]
@laf0rge Sounds like a good plan. I'll close this request since it's redundant

**Pull request closed without merging**
